name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DEBUG: "1"
        SECRET_KEY: 'test_key'
        DATABASE_ENGINE: 'django.db.backends.sqlite3'
        DATABASE_NAME: ./db.sqlite3
        DATABASE_USER: "test"
        DATABASE_PASSWORD: "senha123"
        DATABASE_HOST: "127.0.0.1"
        DATABASE_PORT: "1111"
      run: |
        python manage.py test
